# Generated by Django 5.1.3 on 2024-11-20 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourAfricaUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
