# Generated by Django 5.1.3 on 2024-11-20 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourAfricaUser', '0002_otp_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_user', to='TourAfricaUser.user'),
        ),
    ]
